#18 Replace {!! with {{   to always escape the data
InfyOmLabs/adminlte-templates pull request #51
Opened 2019-11-09 11:44 UTC by ajayinfyom

#18 Replace {!! with {{   to always escape the data

2019-11-11 04:49 UTC, mitulgolakiya requested changes

2019-11-11 04:49 UTC, mitulgolakiya commented on templates/scaffold/fields/boolean.stub
> +    {{ Form::label('$FIELD_NAME$', '$FIELD_NAME_TITLE$:') }}
need to revert it back.

2019-11-29 11:55 UTC, vishalinfyom approved these changes

2019-11-30 02:59 UTC, mitulgolakiya requested changes

2019-11-30 02:59 UTC, mitulgolakiya commented on templates/scaffold/auth/login.stub
> +            {{ csrf_field() }}
I think we should use https://laravel.com/docs/5.8/blade#csrf-field

2019-11-30 08:44 UTC, mitulgolakiya approved these changes

2019-11-30 08:44 UTC, merged